version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      BINDING: 0.0.0.0
    volumes:
      - app_volume:/app_root
      - app_bundle:/usr/local/bundle
    ports:
      - 3000:3000

volumes:
  app_volume:
  app_bundle:
